# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected', to='loginReg_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='chingoo', through='loginReg_app.Relationship', to='loginReg_app.User'),
        ),
    ]
